/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleStorage } from "./SimpleStorage";

export { SimpleStorage__factory } from "./factories/SimpleStorage__factory";
